### ISSUE TITLE
Syntax highlighting for YAML header block

### ISSUE THREAD

**Issue by karlmoller** [fernandomayer/spacemacs#1]
Is there a trivial way to highlight the YAML header block (between pair  of ---) in an RMarkdown file?

**Comment by Adrianzo** [comment]
IDK. but this is related: https://github.com/vspinu/polymode/issues/114

**Comment by fernandomayer** [comment]
Shame on me... sorry but I didn't see this message before.

Anyway, syntax highlighting in YAML blocks are now enabled by default, right? (For me it is).

Thanks.

**Comment by nalzok** [comment]
**Update:**

Ah I guess it was my fault! Highlighting works fine after I installed `YAML-mode` and re-enabled polymode.

------

No it isn't enabled by default for me... Here is a screenshot. What additional information do you need?

![screen shot 2019-03-01 at 22 46 58](https://user-images.githubusercontent.com/13443062/53645488-f15fbe00-3c73-11e9-8329-ad68764e9e59.png)

**Comment by fernandomayer** [comment]
@sunqingyao that's the same highlighting I get.

I just enabled the `yaml` layer in `.spacemacs`.
